### ISSUE TITLE
[Bug]: Frontend loads sometimes slow

### ISSUE THREAD

**Issue by Bascht74** [nurikk/z2m-frontend#1124]
### What happened?

Hi, 

I am using the HA-Addon. 
I got some UI issues when loading the frontend. Other people seems to have it, too: https://github.com/zigbee2mqtt/hassio-zigbee2mqtt/issues/236

I tried to see, if direct access to the port fixes that (by adding port 8099 to the add-on configuration). 
Here the rendering is OK, but every second time or so it takes very long to load...

The following file seems to be the cause: 
http://homeassistant:8099/scripts/vendor.49fee1be1555be7ec8f9.js
and sometimes the css files...

![image](https://user-images.githubusercontent.com/66269310/144140799-37a6d3ad-7550-45b5-bf15-8e010ae5cc38.png)

If it doesn't work, a reload takes forever to load (still spinning):
![image](https://user-images.githubusercontent.com/66269310/144141130-55b705ed-db8b-48f3-8e52-afb8576e1eeb.png)

### What browsers are you seeing the problem on?

Chrome

### Relevant stacktrace

```shell
? Please provide some info how to get this..

If a state.json.zip is needed, I can provide it.
```

### Did you donwload state.json.zip?

I will not attach state.json.zip

**Comment by Bascht74** [comment]
Some info about my setup:
![image](https://user-images.githubusercontent.com/66269310/144141349-305df090-e4d4-4a5d-8842-1fa7b2c06882.png)

**Comment by Bascht74** [comment]
Found out that these "hangs" are only there if you reload/load:
http://homeassistant:8099/# (devices)

If you load/reload another page, e.g. http://homeassistant:8099/#/settings/settings
it load always fast. You can even switch over to the devices very fast.

If you reload http://homeassistant:8099/# again, it is very slow again...
(I can record a video if you like!)

Maybe this information helps...

**Comment by Bascht74** [comment]
http://homeassistant:8099/#/settings/settings reloads very fast and you can switch to every tab (devices, OTA) very fast.
If you load/reload http://homeassistant:8099/#/ota there is a delay as well. I takes some time sometimes. But still loads fast. 

-> Maybe a timing issue in the devices tab?

If I use ingress, everything behaves  the same, but a bit worse.
If I load/reload http://homeassistant:8123/api/hassio_ingress/xb7LC6wY8k-YRkNRfoE5t_AWau1HpMH6soEhQwWF4Q4/#/settings/settings --> all Ok
If http://homeassistant:8123/api/hassio_ingress/xb7LC6wY8k-YRkNRfoE5t_AWau1HpMH6soEhQwWF4Q4/#/ --> hangs very often or shows nothing or black background (no css loaded). If it hangs, chrome is not responding anymore, you can click reload, but nothing happens for a long time...

**Comment by nurikk** [comment]
Hi, thanks for detailed issue description. Let me check

**Comment by nurikk** [comment]
I've made few optimisations, it should get better from today release or dev branch

**Comment by nurikk** [comment]
Hi, try to switch to the latest dev branch

https://www.zigbee2mqtt.io/advanced/more/switch-to-dev-branch.html#switch-to-the-dev-branch

**Comment by Bascht74** [comment]
Hi, 

tried it. Now I have:
![image](https://user-images.githubusercontent.com/66269310/144312395-d27b32fd-0e42-4d54-b33e-9b40c2e62c8f.png)

HA-Version:
![image](https://user-images.githubusercontent.com/66269310/144312561-07cbed40-8626-4925-9daf-83da6551a5db.png)

I recorded a video of this behavior. It is still there and only on the device tab!: 
https://youtu.be/CqJWvxgKco0

Maybe it helps you to see something. 

More findings: 
- If it hangs while loading you can go e.g. to OTA (click on OTA) and then the device page will be loaded after a second (it doesn't go to OTA). Somehow clicking a link to another page helps. 
- the device information is not received while it hangs. All devices show "offline".

Can you delay the switching of protocols (HTTP 101) to /api / websocket for a second or until all assets HTML, CSS, JS, pics ...) are fully loaded/rendered?
Maybe that step sometimes come too early...

See wireshark:
![image](https://user-images.githubusercontent.com/66269310/144318149-dd53e4c7-f69a-47c0-b39c-916903ca6a16.png)

Seb

a workaround would be if you can set the start tab that will be presented if you load the base URL.

**Comment by nurikk** [comment]
I've checked, it seem there are some issues with ingress. It prevents caching and streams content as plain text, without any compression.

**Comment by Bascht74** [comment]
Ok, but the video I made was without ingress. I enabled direct access through port 8099. The issue is there as well.

I wanted to see weather ingress is responsible for this behavior as well. That’s why I used 8099 without ingress. 

In Ingress everything is ok as well if you use the ingress link to the OTA tab and you switch to devices. If you access devices directly —> Problem.

A workaround would be if it is possible to select a main tab that is opened with the main URL.

**Comment by Bascht74** [comment]
If you want to take a look„live“ we could use e.g. teamviewer or ms teams.

**Comment by luberan** [comment]
I installed he Edge version of zigbee2mqtt add-on and no change, still loading and never loads. I am available for a teams call if you are willing to do some troubleshooting.

**Comment by Bascht74** [comment]
Something must be different between the OTA page and the devices page and their behavior while loading the page…

Can you tell me where these pages are saved in the file path. Maybe I can play with them…

**Comment by nurikk** [comment]
> Ok, but the video I made was without ingress. I enabled direct access through port 8099. The issue is there as well.
> 
> I wanted to see weather ingress is responsible for this behavior as well. That’s why I used 8099 without ingress.
> 
> In Ingress everything is ok as well if you use the ingress link to the OTA tab and you switch to devices. If you access devices directly —> Problem.
> 
> A workaround would be if it is possible to select a main tab that is opened with the main URL.


how did you managed to open it without ingress?

**Comment by nurikk** [comment]
Okay, I've changed frontend port to `8485` (configured for Socat tcp-listen port) and can access frontend. And I see everything works fine

**Comment by nurikk** [comment]
Can you send me a screenshot of network tab? Like this
<img width="1440" alt="Screenshot 2021-12-02 at 7 40 13 PM" src="https://user-images.githubusercontent.com/1525421/144415378-910dd599-2d3a-4915-8e2f-301ff4e81826.png">
b?

**Comment by nurikk** [comment]
and configure your z2m like this. and open browser using this port?

<img width="582" alt="Screenshot 2021-12-02 at 7 44 38 PM" src="https://user-images.githubusercontent.com/1525421/144415995-cd66a5b6-c3bc-4fa4-8cac-febccfcc0e6e.png">
s:

**Comment by Bascht74** [comment]
> > Ok, but the video I made was without ingress. I enabled direct access through port 8099. The issue is there as well.
> > I wanted to see weather ingress is responsible for this behavior as well. That’s why I used 8099 without ingress.
> > In Ingress everything is ok as well if you use the ingress link to the OTA tab and you switch to devices. If you access devices directly —> Problem.
> > A workaround would be if it is possible to select a main tab that is opened with the main URL.
> 
> how did you managed to open it without ingress?

I forked it and added the port: 
https://github.com/Bascht74/hassio-zigbee2mqtt

If you add this via HA, you can use Port 8099 with the add-on as well as via ingress.
But your way is much easier I must confess. Use the Socat port... great idea...

**Comment by luberan** [comment]
When I changed the port number, access via HA panel gives me 502: Bad Gateway. When I try accessing it directly via localip:8485 I get again just loading , please wait...
![image](https://user-images.githubusercontent.com/35958932/144417456-637923ac-0369-4b14-a75e-03fe7a5ca121.png)

**Comment by Bascht74** [comment]
> When I changed the port number, access via HA panel gives me 502: Bad Gateway. When I try accessing it directly via localip:8485 I get again just loading , please wait... ![image](https://user-images.githubusercontent.com/35958932/144417456-637923ac-0369-4b14-a75e-03fe7a5ca121.png)

That is normal as ingress expects the other port...
But for my test I will do it that way as I want to have as less difference as possible.

**Comment by nurikk** [comment]
> > When I changed the port number, access via HA panel gives me 502: Bad Gateway. When I try accessing it directly via localip:8485 I get again just loading , please wait... ![image](https://user-images.githubusercontent.com/35958932/144417456-637923ac-0369-4b14-a75e-03fe7a5ca121.png)
> 
> That is normal as ingress expects the other port... But for my test I will do it that way as I want to have as less difference as possible.

open `http://ipaddress:8485` after this operation

**Comment by luberan** [comment]
I did and could see the frontend, but with the same issue "loading, please wait" on the devices tab.

**Comment by nurikk** [comment]
> I did and could see the frontend, but with the same issue "loading, please wait" on the devices tab.

can you send me screenshot from chrome dev tools? network tab. and btw do you have any devices joined your z2m?

**Comment by luberan** [comment]
![image](https://user-images.githubusercontent.com/35958932/144419762-d8daddca-cff4-4228-b4e8-f7cb32a2ad57.png)
[192.168.89.241.txt](https://github.com/nurikk/zigbee2mqtt-frontend/files/7641718/192.168.89.241.txt)

No devices yet joined.

**Comment by Bascht74** [comment]
> Okay, I've changed frontend port to `8485` (configured for Socat tcp-listen port) and can access frontend. And I see everything works fine

OK, I used the original add-on again and changed the frontend port to 8485:
![image](https://user-images.githubusercontent.com/66269310/144418852-b3f087ab-176f-4d6d-82b2-26fe150f096d.png)

First run:
![image](https://user-images.githubusercontent.com/66269310/144419064-4952b9c3-ffbc-4b94-8793-11f596b1ae08.png)

Reload: 
(Loading 5-6 Seconds):
![image](https://user-images.githubusercontent.com/66269310/144419183-28dbd24e-054b-4f58-8b36-d5afad4edac5.png)

Reload again:
![image](https://user-images.githubusercontent.com/66269310/144419487-e95d97da-93a2-4bcd-926f-9180dcbd9d15.png)
--> not loading, still spinning.

after some time:
![image](https://user-images.githubusercontent.com/66269310/144419594-b08db470-394e-446e-8414-dab5d58f44f3.png)

and some time later:
![image](https://user-images.githubusercontent.com/66269310/144419638-6ebc957e-07d0-4d5f-b884-976dada1e363.png)

Try to reload the devices page a couple of times after the page is shown --> hangs sometimes.
Try to reload the OTA page a couple of times --> takes some seconds --> OK

**Comment by nurikk** [comment]
> ![image](https://user-images.githubusercontent.com/35958932/144419762-d8daddca-cff4-4228-b4e8-f7cb32a2ad57.png) [192.168.89.241.txt](https://github.com/nurikk/zigbee2mqtt-frontend/files/7641718/192.168.89.241.txt)
> 
> No devices yet joined.

Oh, this is confusing spinner, it should show just empty table header. In your case if you join a device you'll be able so see devices table. I've removed this spinner in latest dev commit

**Comment by nurikk** [comment]
> > Okay, I've changed frontend port to `8485` (configured for Socat tcp-listen port) and can access frontend. And I see everything works fine
> 
> OK, I used the original add-on again and changed the frontend port to 8485: ![image](https://user-images.githubusercontent.com/66269310/144418852-b3f087ab-176f-4d6d-82b2-26fe150f096d.png)
> 
> First run: ![image](https://user-images.githubusercontent.com/66269310/144419064-4952b9c3-ffbc-4b94-8793-11f596b1ae08.png)
> 
> Reload: (Loading 5-6 Seconds): ![image](https://user-images.githubusercontent.com/66269310/144419183-28dbd24e-054b-4f58-8b36-d5afad4edac5.png)
> 
> Reload again: ![image](https://user-images.githubusercontent.com/66269310/144419487-e95d97da-93a2-4bcd-926f-9180dcbd9d15.png) --> not loading, still spinning.
> 
> after some time: ![image](https://user-images.githubusercontent.com/66269310/144419594-b08db470-394e-446e-8414-dab5d58f44f3.png)
> 
> and some time later: ![image](https://user-images.githubusercontent.com/66269310/144419638-6ebc957e-07d0-4d5f-b884-976dada1e363.png)
> 
> Try to reload the devices page a couple of times after the page is shown --> hangs sometimes. Try to reload the OTA page a couple of times --> takes some seconds --> OK
<img width="653" alt="Screenshot 2021-12-02 at 8 25 42 PM" src="https://user-images.githubusercontent.com/1525421/144421624-cd13a0f6-2560-47d0-bbbc-c237501e8870.png">

Can you export network history (all cases, ingress + direct port access) as HAR dump?

**Comment by Bascht74** [comment]
Here is the first one via ingress:
[ingress.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7646028/ingress.zip)

console: 
![image](https://user-images.githubusercontent.com/66269310/144526672-3ebb957e-9113-47df-b92a-b8755496bd01.png)

result:
![image](https://user-images.githubusercontent.com/66269310/144526724-0616f322-e8e3-4e58-b7d5-a4e2bd6794e3.png)

noticeable: If I open the devices tab --> at first all devices are offline. After 30 seconds or so they are online. But if you - after loading the devices tab -> devices offline - switch over to any other tab and switch right back to devices, the devices are online right away..

If this is OK that way, I will add the other...

**Comment by Bascht74** [comment]
@nurikk 
Is there a way to test a workaround so that "/" opens e.g. dashboard and not devices as start tab. That would be even a good idea to have the possibility to select a starting point. For this test, a static change in the Sourcecode would fit. 

Is there a way to get rid of the pics in the devices, just to check if it changes something (this is most noticeable difference between devices and OTA-Tab)? But I don't know what is the most effective way how to do that. I am able to change a files in the docker container.

**Comment by nurikk** [comment]
Can you send me HAR dump from direct connection? using `8485` port

**Comment by tteck** [comment]
I'm running bare-metal and have the slow loading frontend.
what I've learned to do is, go directly to the settings tab and back to the devices tab and everything is loaded
saves a minute or so waiting

**Comment by nurikk** [comment]
> I'm running bare-metal and have the slow loading frontend. what I've learned to do is, go directly to the settings tab and back to the devices tab and everything is loaded saves a minute or so waiting

Hi, can you install this app? https://github.com/vi/websocat#installation
and then execute 
`websocat ws://192.168.1.200:8080/api > onConnect.json`
(replace 192.168.1.200:8080 with your host ip and port) and then share onConnect.json with me?


and also network HAR dump from chrome dev tools

<img width="653" alt="Screenshot 2021-12-02 at 8 25 42 PM" src="https://user-images.githubusercontent.com/1525421/144695514-18f1bccb-27dc-4bd3-8d4e-4375318184dc.png">

**Comment by nurikk** [comment]
Should be fixed now, can you check on latest dev branch?

**Comment by tteck** [comment]
WOW! Thank you for all of your hard work. It indeed is fixed, and fast!

**Comment by nurikk** [comment]
We still have small issue with hassio addon

**Comment by Bascht74** [comment]
@nurikk Hi, I was not too well the other days. Sorry that I didn't respond. 
As I can see, you found it! Great! My slow loading is now gone, even in the devices tab!

There are two (quite) smaller issues left in the HA addon:
1. Sometimes the CSS ist not loaded correctly. Reload helps (mayby 2-3 time)
[ingress2.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7656224/ingress2.zip)
![image](https://user-images.githubusercontent.com/66269310/144752991-68e8ab55-148e-481f-84f3-97ddbf2d6d30.png)

2. Sometimes you get only a white screen. Reload helps (mayby 2-3 time):
[ingress.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7656217/ingress.zip)
![image](https://user-images.githubusercontent.com/66269310/144752922-363cbc48-6c9f-4966-a4d8-48f76a188908.png)


I tried to understand you code a bit and two things I was wondering about:
1. In ws.js:
```
const wss = new WebSocket.Server({
    port: 8579,
```
Is this file ignored or the port internally used? 
Port 8579 is not open to my knowledge in the HA environment.

2. I found some references like this in the Code. 
```
Node-version
        with:
          node-version: 16
```
The HA addon seems to use Alpine Linux 3.14 (3.15 is out but not used in HA / for the docker-package so far). 3.14 = Node.js 14.17.0, 3.15 = nodejs 16.13 (LTS) / nodejs-current 17.0. 
Would it help anyhow to use the newer 3.15 version (with newer node.js) for the docker-image?

Thx anyway for fixing the strong delay / reload issue!

Seb

**Comment by tteck** [comment]
0.6.57 loading slow again

**Comment by Bascht74** [comment]
I cannot confirm this. Still working good…
Version installed:

0.6.57

tteckster ***@***.***> schrieb am So. 5. Dez. 2021 um 20:01:

**Comment by tteck** [comment]
I'm definitely back to a minute or more to load. 
0.6.55 was fast!

**Comment by nurikk** [comment]
> 0.6.57 loading slow again

can you send me HAR report from chrome dev tools?

**Comment by tteck** [comment]
> > 0.6.57 loading slow again
> 
> can you send me HAR report from chrome dev tools?
[192.168.86.104.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7657594/192.168.86.104.zip)

**Comment by nurikk** [comment]
> > > 0.6.57 loading slow again
> > 
> > 
> > can you send me HAR report from chrome dev tools?
> > [192.168.86.104.zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7657594/192.168.86.104.zip)

the file is 0 bytes size.
How to record HAR archive:
1) Open chrome dev tools on frontend page
2) Refresh the page
3) Export HAR

**Comment by tteck** [comment]
[192.168.86.104 (1).zip](https://github.com/nurikk/zigbee2mqtt-frontend/files/7657672/192.168.86.104.1.zip)

**Comment by nurikk** [comment]
> I'm definitely back to a minute or more to load. 0.6.55 was fast!

fixed, thanks

**Comment by tteck** [comment]
0.6.58 fixed my problem! Thanks

**Comment by cpuks** [comment]
Is this issue sorted as I have to stay on stable branch due to lack of time. Maybe someone with running z2m on bare metal can confirm? As I was pulling my hair off - it wasn't easy to find that issue. Glad it's addressed.

**Comment by blackwiz4rd** [comment]
I can confirm this version also solved my problems in loading the frontend. Nice job and thanks.

**Comment by Bascht74** [comment]
Yes, but the ingress bug is still happening. So I will close this issue, because it is not about it.

**Comment by litecross91** [comment]
Slow me again.
